--Get all Customer Details
select * from Customer

--Get all Customer Orders. CustomerId, OrderId
select [Name],[OrderId],[Id] from Customer, Orders where Orders.CustomerId=Customer.Id 

--Get total revenue generated by Customer Name = 'Anu'
select Sum(Cost) from Orders,Customer,Product where Orders.CustomerId=Customer.Id AND Orders.ProductId=Product.Id AND Customer.Name='Anu'

--Get Order Details for cost > 900
select [OrderId],[Name] from Orders, Product where Cost > 900 AND Orders.ProductId=Product.Id

--Get Order Details for Dates between Oct 1, 2022 and Oct 30, 2022
select * from Orders where OrderDate between '2022-10-01' AND '2022-10-30'

--Get Customer Name, Product Name Purchased, Product Cost for all customers
select Product.Id,Product.Name,Product.Cost,Orders.OrderId,Customer.Name  from Customer,Product,Orders where Orders.ProductId=Product.Id AND Orders.CustomerId=Customer.Id

-- Get All Customers that contain third letter as 'd' and last letter as 'a'
select * from Customer where Name LIKE '__d%a'