USE Eshop

--This is a comment
--Get all products 
Select * from Product

--Get all products that have categoryid = 10
select * from Product where CategoryId=10

--Get total cost of products listed with categoryid =10
select Sum(Cost) from Product where CategoryId=10

--Get product name , cost 
select Name,Cost from Product

--Save above result as view
CREATE VIEW vw_Product as (select Name, Cost from Product)

--See the view result
select * from vw_Product

--Get all products that start with K
select * from Product where Name Like 'K%'

--Get all products where u is a second letter
select * from Product Where Name Like '_u%'

--Get all products whose product cost is not equal to 5000
select * from Product where cost <> 1000

--Get all products where name starts with T and ends with S
select * from Product where Name Like 'T%s'

--select all products with names as 'T-shirt', 'ipad','kurti'
select * from Product where Name='T-Shirts' OR Name='Ipad' OR Name='Kurti'

--better technique
select * from Product where Name in('T-Shirts','Ipad','Kurti')

--Get all products having a category id matching a category in ProductCategory table
select * from Product where CategoryId IN(select Id from ProductCategory)

--Get name and orderid for all customer
select [Name],[OrderId] from Customer, Orders where Customer.Id=Orders.CustomerId

--Get total revenue generated by shivangi
select Sum(Cost) from Orders,Customer,Product where Orders.CustomerId=Customer.Id AND Orders.ProductId=Product.Id AND Customer.Name='Shivangi' 